version: '3'
services:

  massa-core:
    image: peterjah/massa-core
    container_name: massa-core
    restart: always
    environment:
      - MASSAGUARD=1
      - DISCORD=${DISCORD}
      - DYNIP=0
      - WALLETPWD=${WALLETPWD}
      - NODE_MAX_RAM=90
      # Set if node registered with massabot - Set with OK if node registrered with massabot or KO if you want to check and use registration process
      - NODE_TESTNET_REGISTRATION=KO
      - TARGET_ROLL_AMOUNT=NULL

    ports:
     - "31244:31244"
     - "31245:31245"
     - "33035:33035"
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
    volumes:
     - ./massa_mount:/massa_mount

volumes:
  massa-core:


